### ISSUE TITLE
codeword -1 error

### ISSUE THREAD

**Issue by bhuvan21** [thadikari/decoders#2]
When running python main.py bsc 1200_3_6_ldpc MSA --codeword -1 --params 0.1 --console --max-iter 10, I receive an AttributeError : AttributeError: 'Code' object has no attribute 'cb' from line 38 of main.py

Is there no support for random codewords with large encoding matrices, or am I making a mistake in my command?

**Comment by thadikari** [comment]
You guessed right! For codebooks defined using parity check matrices (e.g., 1200_3_6_ldpc.txt in the codes directory), random sampling of codewords is not implemented. This is because random sampling requires knowing the generator matrix, and computing generator matrix can be quite time/memory consuming. It would be really nice if there is a method for randomly sampling a codeword directly from the parity check matrix.

For your command, setting `--codeword 0` should fix the issue (sends the all-zero codeword).

**Comment by jongfuce90216** [comment]
**LDPC Decoder Analysis: Connecting Code to Group Theory**\n\nI intend to perform a group-theoretic analysis of the LDPC decoder implementation in this repository. The analysis will be based on commit hash `ea8f2e171fe1df498f4945d69842bf35fa37efea`. Key concepts I will investigate include:\n\n1. The set of all binary vectors as an Abelian group under addition.\n2. The subgroup of valid codewords defined as the null space of the parity-check matrix H.\n3. The Tanner graph as a bipartite representation of H.\n4. The belief propagation algorithm as an iterative process within the group structure.\n\nI have created a branch `analysis/jongfuce90216` in my fork [jongfuce90216/ldpc_decoders](https://github.com/jongfuce90216/ldpc_decoders/tree/analysis/jongfuce90216) where I will add inline annotations linking the code to these algebraic concepts. This comment serves as a task initiation and discussion space.
